# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

pool:
  name: Azure Pipelines

variables:
  name: Yash
  imageName: python-app
  acr-registry: acrtestregistry12.azurecr.io

stages:
  - stage: Build
    displayName: Build stage1
    jobs:
    - job: 
      displayName: 'Run one-line script'
      steps:

      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: 17.09.0-ce
          releaseType: stable 

      - task: HelmInstaller@0
        inputs:
          helmVersion: '3.14.2'
          installKubectl: true
          kubectlVersion: '1.30.0'
      
      - script: |
          echo Hello, $(name).!
          echo System.DefaultWorkingDirectory: '$(System.DefaultWorkingDirectory)'
          echo Pipeline.Workspace: '$(Pipeline.Workspace)'
          echo Build.ArtifactStagingDirectory: '$(Build.ArtifactStagingDirectory)'
          pwd
          echo Helm version:
          helm version --short
          echo kubectl version:
          kubectl version
          echo Docker execution
          docker ps -a
